(define (problem legoConditionalTestnditionalTest-prob)
  (:domain legoConditionalTest)
  (:objects red2x4 black2x2 white2x2 - lego brd - board i - int)
  (:init (= (total-board-space brd) 16)
         (= (total-area red2x4) 8)
         (= (total-area black2x2) 4)
         (= (total-area white2x2) 4)
         (= (taken-space brd) 0)
         (= (exposed-space brd) 16)
         (inbox red2x4)
         (inbox white2x2)
         (inbox black2x2)
         (= (const1 i) 1)
         (= (const2 i) 2))
  (:goal (and
                (attached red2x4)
                (attached white2x2)
                (attached black2x2)
                (= (exposed-space brd) 0)
                (= (taken-space brd) 16)))
)

