(define (problem test-problem)
  (:domain test-domain)
  (:objects ups-box cereal-box - box)
  (:init (parked goldie)
	 (holding ups-box)
	 (in cereal-box goldie)
	 (= (fuel-level goldie) 7))
  (:goal (and (in ups-box goldie) 
	      (>= (fuel-level goldie) 9))))
